### ISSUE TITLE
Detting docker error

### ISSUE THREAD

**Issue by alarmatwork** [MiniAiLive/LPR-Docker#2]
I have followed your startup guide and got following error:

``` docker-compose up -d
[+] Running 4/4
 ✘ broker Error
 ✘ mongodb Error
 ✘ nodered Error
 ✘ redis Error 

Error response from daemon: pull access denied for openlpr/nodered, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by Patrick-Kladek** [comment]
@alarmatwork were you able to solve this? I have the same issue right now.

**Comment by alarmatwork** [comment]
> @alarmatwork were you able to solve this? I have the same issue right now.

Sorry no. It seemed to be conf issue of the specific platform.
